### ISSUE TITLE
dali.tests.test_dummy.DummyDriverFixtureParts.log

### ISSUE THREAD

**Issue by sde1000** [sde1000/python-dali#113]
@sl-wallace 

I had to alter the type hint for `DummyDriverFixtureParts.log` in `tests/test_dummy.py` because `py._path` no longer exists in the test runner. Can you have a look and see if what I did makes sense? It's in commit 7617e9a4a978fafc1e044bc91b7a2068d5c239ff

The pytest documentation referred to in your comment no longer seems to say anything relevant.

**Comment by sl-wallace** [comment]
Yeah seems fine to me! Serves me right for using a `_` prefixed method anyway.
