### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by rnixx** [sde1000/python-dali#12]
Do you mind if i format the code according to PEP8?

**Comment by sde1000** [comment]
I thought @caiwan already did - but if there are parts he missed, please do reformat.  If you're making substantial changes, I suggest you rebase your tree on my current master so I can take your commit directly rather than having to cherry-pick it.

**Comment by sde1000** [comment]
(It's just a git style thing - I dislike having branches/merges in the history that could trivially have been avoided if the author of a pull request had rebased their tree before generating the pull request.  I'm happy to have branches/merges for larger features or where a rebase wouldn't have been trivial.)

**Comment by rnixx** [comment]
i've seen that @caiwan has been working on code restructuring, but it not seems there has anything been done related to PEP 8.

@caiwan - what's the state of your restructuring, is there any chance this can be merged soon?

Otherwise i would suggest formatting the code PEP 8 in the first place and do restructuring where appropriate afterwards... ?

**Comment by caiwan** [comment]
Perhabs I have missed a few things when I was reformatting it. I was following Pycharm's guidance during the reformatting. 
I'll not reconstruct the code at the moment; I'll add the serial support soon.

**Comment by rnixx** [comment]
@caiwan That means your formatting already has been merged into master?

**Comment by caiwan** [comment]
Had been somewhere a month ago.

**Comment by rnixx** [comment]
ok, thanks

**Comment by caiwan** [comment]
I found it: [This commit](https://github.com/sde1000/python-dali/commit/40b3c27214ba0a308015358a9cbcd7672d7736b7)

**Comment by sde1000** [comment]
A commit with formatting fixes from @rnixx has now been pushed to master.
