### ISSUE TITLE
No module named 'dali.interface'

### ISSUE THREAD

**Issue by mohandas22** [sde1000/python-dali#123]
Hi,
If I go to https://github.com/sde1000/python-dali/blob/master/examples/set_single.py 
In the line number 6 "from dali.interface import DaliServer", we can see dali.interface. 

But dali has module named interface. https://github.com/sde1000/python-dali/tree/master/dali

**Comment by sde1000** [comment]
The example is very out-of-date. It would need to import an appropriate driver from `dali.driver` instead.
