### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by TA1DB** [sde1000/python-dali#131]
Hi,

I am using Hasseb Dali Master with it's GUI on Windows 11 without any difficulty.

When I try find_ballasts.py on the same machine I get "ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it"

Could anyone give me a hand to resolve my this issue. Thanks in advance.

**Comment by sde1000** [comment]
The `find_ballasts.py` example is written to use DaliServer. If you want to use it with a Hasseb device you need to edit it to use that driver instead.

The `find_ballasts.py` example isn't particularly useful — it doesn't do anything once it's found them. You may find the `async-commissioning.py` example more useful.

**Comment by TA1DB** [comment]
Thanks. What should I enter as the device in Windows instead of this : " --device /dev/dali/hasseb-* "
