### ISSUE TITLE
Driver Interface

### ISSUE THREAD

**Issue by caiwan** [sde1000/python-dali#16]
Create an intrface class to make different drivers with it. (Sucha as tridonic USB, UART, DaliServer... etc) I've created one, but it made a merge conflict due I couldn't catch up the recent changes.

* Collect the common functions in [`interface.py`](https://github.com/caiwan/python-dali/blob/dev-uart/dali/interface.py) in a base class
* Derive every class from it. Keep `interface.py` for contain interface for various drivers.
	* [`driver/uart.py`](https://github.com/caiwan/python-dali/blob/dev-uart/dali/driver/uart.py)
	* [`driver/daliserver.py`](https://github.com/caiwan/python-dali/blob/dev-uart/dali/driver/daliserver.py)

I've seen vou've created a new branch for serial communication, but I had my own [here](https://github.com/caiwan/python-dali/tree/dev-uart) as a feature branch.

**Comment by caiwan** [comment]
If anyone could poperly merge it, I'd appreciate that, since I've consideret I'd mess this up very quicly.

**Comment by sde1000** [comment]
Yes, it needs tidying up - I'll look at it soon, and merge your driver too if that's OK with you.  The interfaces don't necessarily need to share a common ancestor class, but they do need to have similar APIs.  It's not yet clear what that API should be - they will ultimately need to work in multi-threaded and event-driven programs, so there needs to be room for experimentation.

The serial driver I just committed is for the Tridonic RS-232 DALI interfaces.  They appear to have a different protocol to the one you're currently writing a driver for - I had a quick look at yours to see if it matched, but it didn't.

**Comment by caiwan** [comment]
I'd recommend to have a naming convention with branches:
- `master` is for all-time working code, with successful tests, etc
- `dev` is for collecting various features, tyding everyting up, make tests work
- `dev-<feature_name>` is for various features. 
I don't really know how to avoid conflicts like this, but keep somhow failsafe. (We need a poper workflow too)

**Comment by sde1000** [comment]
Really not necessary with a distributed version control system.  Name branches in your tree whatever you like!  In my tree I will try to keep the "master" branch in a working state.

**Comment by caiwan** [comment]
Would you take a look at my code?

**Comment by sde1000** [comment]
I have rebased your UART driver onto my master branch; there were only minor merge conflicts.  You can find it in my branch "caiwan-dev-uart".  I haven't looked at the code beyond fixing merge conflicts and checking that the tests still run.

**Comment by caiwan** [comment]
Thanks, I'll take a look at them, and create a pull request today.
