### ISSUE TITLE
Using setuptools instead of distutils in setup.py

### ISSUE THREAD

**Issue by rnixx** [sde1000/python-dali#20]
Is there a specific reason why you use plain distutils in setup.py instead of setuptools?

**Comment by sde1000** [comment]
No particular reason, I started using distutils in my projects before setuptools existed and never got around to changing.

**Comment by sde1000** [comment]
Also, I see that setuptools is an external dependency; it's still not part of the standard library.  I would need a compelling reason to change rather than a reason not to change!

**Comment by rnixx** [comment]
According to https://python-packaging-user-guide.readthedocs.org/en/latest/current/ and the accepted answer at http://stackoverflow.com/questions/6344076/differences-between-distribute-distutils-setuptools-and-distutils2, setuptools is the most popular out there right now.

Actually i have to admit that I don't know the exact differences between these tools. I just use setuptools since ever so I wanted to know whether there's a reason to prefer distutils.

**Comment by rnixx** [comment]
To sum this up, maybe just switch to setuptools once it's really necessary.
