### ISSUE TITLE
Package License

### ISSUE THREAD

**Issue by rnixx** [sde1000/python-dali#4]
Hi,

would you mind license this package under LGPL, MIT, APACHE or similar license?

Regards

**Comment by sde1000** [comment]
I might consider LGPL, but for a Python package I don't see what it gains you over GPLv3.  Can you explain what you want to do that's currently not possible?

**Comment by rnixx** [comment]
I can't use your code in a non GPL project right now. IMHO GPL is good for complete software solutions, for libraries and frameworks i'd prefer less restrictive licensing.

**Comment by sde1000** [comment]
I'm willing to add LGPLv3 to the licence.

Just a note, though - this library is still at a very early stage, and the API is neither complete nor stable.  Use with care, and be prepared for things to break when you pull an update.

**Comment by rnixx** [comment]
Ok, sounds good. Prior to investigate deeper whether to use a piece of software or not i need to make sure i get no licensing issues.

Anyway, i'm going to try it out the next 2-3 weeks, and of course, i'm willing to make contributions in form of tests or whatever is necessary.

Thanks for your work!

**Comment by rnixx** [comment]
How should the license change should be organized in code? Add LICENSE-LGPL file next to LICENSE? How should the changes be reflected in debian/copyright?

**Comment by sde1000** [comment]
I followed (some of) the advice at http://www.gnu.org/licenses/gpl-howto.html

**Comment by sde1000** [comment]
Ugh, sorry for the force-pushes.  I'm clearly not awake yet!
