### ISSUE TITLE
UART / Serial support

### ISSUE THREAD

**Issue by caiwan** [sde1000/python-dali#5]
I do have a custom contorller, which is able to communicate through (virtual) serial port with dali devices. It would nice to have a driver which is able to do that.

**Comment by sde1000** [comment]
Well, it's your controller - only you know how to drive it!  You may find the pyserial library useful.

**Comment by caiwan** [comment]
Allright, I'll push a I'm getting done with it. I just wanted to write it here as a future feature.

**Comment by caiwan** [comment]
I've created a feature branch for it: [caiwan/dev-uart](https://github.com/caiwan/python-dali/tree/dev-uart)

**Comment by rnixx** [comment]
I guess this issue can be closed in favour of https://github.com/sde1000/python-dali/pull/21
