### ISSUE TITLE
Dali groups

### ISSUE THREAD

**Issue by beireken** [sde1000/python-dali#55]
Just wondering, do you have plans to include dali groups to be added?
At the moment only lamps are supported, not groups, right?

**Comment by sde1000** [comment]
Groups are supported.

All dali control gear can be added to any set of the 16 available groups.  Commands can be addressed to groups as well as to individual control gear.  See `dali.address.Group` and the commands `dali.gear.general.AddToGroup` and `dali.gear.general.RemoveFromGroup`

**Comment by beireken** [comment]
ok, thx for clearing that up!
