### ISSUE TITLE
Python 2 compatibility

### ISSUE THREAD

**Issue by sde1000** [sde1000/python-dali#56]
Does anybody still care about python 2 compatibility for python-dali?

The next lot of code I plan to commit is python 3.5+ only, because it's based on asyncio.  Committing it won't break python 2 compatibility for existing code, but I'm just wondering about opportunities for clean-up.

**Comment by rnixx** [comment]
I'm fine with dropping python 2 support.

**Comment by dgomes** [comment]
I also support python3.5+

**Comment by tobiasoort** [comment]
I just migrated my whole stack over to python 3.5 because that's the way the world works now. I'm fine with dropping py2.

**Comment by mhemeryck** [comment]
Currently in the process of migrating our entire code base at work over the python3 (bit late of the party, I know). Let me know if you could use some help with that, figure it might be a nice opportunity for me to also learn a bit more of this repo.

**Comment by sde1000** [comment]
Ok, the consensus appears to be that it's fine to drop support for python <3.5.  I'll remove it from the testing and packaging infrastructure soon, and after that there can be a gradual cleanup of python 2.7 compatibility code.  I'll leave this issue open until that cleanup is complete.
