### ISSUE TITLE
DALI Logger on RPi

### ISSUE THREAD

**Issue by DMartin90** [sde1000/python-dali#58]
Hi,

I found this googling for a DALI Logger i could run on a Raspberry Pi
I'm a lighting controls integrator based in Canberra Australia, and we're having trouble with a job that has issues with lights being triggered at odd times with no obvious explanation.
I have very little coding experience, especially not with python. Could anyone help me to build an image I could load onto a Raspberry Pi and connect using a Tridonic DALI USB to the Dali line? even better if it could monitor multiple DALI-USBs and record to files.  Thats all i really want it to do, just record the traffic and store to a text file that i can pull out later. 

I noticed someone mentioned they were short of hardware to further develop this, I have a whole bunch of surplus/older hardware I'm happy to post if someone is interested in helping me out.

**Comment by sde1000** [comment]
Hi,

Yes, the `examples/async-buswatch.py` script should do pretty much exactly what you want.  If you're monitoring multiple DALI-USBs then I could add a command-line parser to it so you can start up multiple instances monitoring each device to a different file.  (Or do you want them all combined?)

Have you managed to get the current example running on a Pi with one DALI-USB?  The procedure should be something along the lines of:

* clone the current python-dali repository (`git clone https://github.com/sde1000/python-dali.git`)

* install it with `setup.py`, or just point PYTHONPATH at it (`export PYTHONPATH=~/python-dali` in your .bashrc, for example, then log in again)

* as root, copy `examples/50-dali-hid.rules` to `/etc/udev/rules.d/` then reboot the Pi or unplug/replug the USB device

* run `examples/async-buswatch.py`

I'm away today, but I'll look at adding command-line parsing to that script soon.  (Or you could adapt the code from `examples/async-commissioning.py`)
