### ISSUE TITLE
Retaining support for python 3.5

### ISSUE THREAD

**Issue by sde1000** [sde1000/python-dali#73]
Leaving this question here because the issue has just come up in the pull request for command sequences:

Is anyone still using this library on python-3.5?

[f-strings](https://www.python.org/dev/peps/pep-0498/) were introduced in python-3.6 and I'm so used to them now it seems odd to have to work around their absence!

Is it now reasonable to drop support for python-3.5?

**Comment by sde1000** [comment]
I notice that f-strings are already in use in the drivers package and nobody has complained...

**Comment by hasseb** [comment]
It should be mentioned somewhere, which version of Python is required. Also other dependencies would be nice to have listed somewhere. In my fork I have rather extensive install instructions. When I first tried sde1000/python-dali it was not very easy to get it work. At least on that time the default Python3 version installed did not support f-strings. It is not very easy to find out whats wrong if you don't know Python and f-strings.

**Comment by rnixx** [comment]
Generally I am not a big fan of "cutting edge" features. I was not aware about the use of f strings in python-dali, otherwise I probably complained. My production setup still uses an older version of python-dali. As rule of thumb I'd prefer backward compatibility as long as reasonable.

**Comment by dgomes** [comment]
I use a simple rule of thumb:

What does Debian stable use ? That's the version I support

**Comment by sde1000** [comment]
Current Debian stable is "buster" which uses Python 3.7.

Other older distributions: Ubuntu 18.04 (supported until April 2023) uses Python 3.6.  Ubuntu 16.04 (supported until April 2021) uses Python 3.5.

I agree with @hasseb that the versions of Python supported should be documented (probably in the README, it's the most obvious place).

So: is anyone still actually using Python 3.5 with python-dali?

**Comment by rnixx** [comment]
> Debian stable is by definition old

Sure, but in terms of embedded system still brandnew :)

However, I'd support 3.5+ until there's a real reason not to do any more.

**Comment by sde1000** [comment]
The main reasons to drop support for 3.5 from my point of view:
* the asyncio API only became stable in 3.6 (although was significantly improved in 3.7 and some of the calls required in 3.6 are now deprecated as of 3.8) — the asyncio-based driver code won't run on 3.5.  I will at some point want to add a test suite for this, which the CI server is going to try to run under 3.5 and fail...
* f-strings :-)
* type annotation syntax was introduced in 3.6 and may be useful to add to the test suite

Even if we decide to retain support for 3.5 for now, I want to have a schedule for removing it.  Significant dates coming up:
* 13 September 2020, the 5th anniversary of the Python 3.5 release
* 23 December 2020, the 4th anniversary of the Python 3.6 release
* April 2021, end of support for Ubuntu 16.04

**Comment by sde1000** [comment]
Nobody has come out and said that they need to use future releases of python-dali with Python 3.5, so I plan to document that it is no longer supported, and remove it from the CI configuration.
