### ISSUE TITLE
publish 0.7 on Pypi ?

### ISSUE THREAD

**Issue by dgomes** [sde1000/python-dali#77]
We haven't published a new version in a while, maybe we can do 0.7 ?

https://pypi.org/project/python-dali/#history

**Comment by sde1000** [comment]
Yes, good idea, a fair bit has changed since 0.6.  I'll have to remind myself how to do it!

**Comment by sde1000** [comment]
Release 0.7 committed at 63bc603830492c79454f654b35e7fafd9910aab3
